### ISSUE TITLE
Set up Recoil state management

### ISSUE THREAD

**Issue by Ali-Jahankah** [SaharNaderi/pink-elephant#14]
We want to set up Recoil state management within our client app; so, we need to save our common states into Recoil store and have access to them without passing them as props to components.
If you don't know what is Recoil, start reading the documentation of Recoil follow the instructions very carefully and set up that.
*DO NOT USE CHATGPT for setting up.

**Comment by SaharNaderi** [comment]
Set Up Recoil ➡️ 😊


![Image](https://github.com/SaharNaderi/pink-elephant/assets/108987674/65882d3f-525c-4c9e-8c45-3810a344fef5)
