### ISSUE TITLE
Create Landing page using TemplatePage

### ISSUE THREAD

**Issue by Ali-Jahankah** [SaharNaderi/pink-elephant#26]
Create a folder in "src" called "pages".
Then create landing page in that.
We want to render all the pages inside PageTemplate.
Something like:

-PageTemplate
      -LandingPage
      -Users
      -User
      -....

 you need to use <OutLine/> as a part of this ticket

You need to know how to work with React Router 6 to do that.

https://dev.to/tywenk/how-to-use-nested-routes-in-react-router-6-4jhd

Please read abvoe article a few times carefully;Then, you can do that.

**Comment by ManaGh** [comment]
can you do this task completely with react router and recoil and gives all of the files such as css,scss,jsx,js 
https://github.com/CodeYourFuture/RainyPlaytime
