### ISSUE TITLE
Reset all the default css from the app

### ISSUE THREAD

**Issue by Ali-Jahankah** [SaharNaderi/pink-elephant#4]
Create a folder called "styles"  in "src" folder. and then create a file called "index.css" in styles.
in "index.css" ; Use "*" to reset margin, padding, outline and border to be "0" and also box-sizing to be "border-box".
The code should looks like this:
*{
border:0;
/rest of the code here.../
}

**Comment by ManaGh** [comment]
The CSS file in src folder has been created, and all box values seted to "0".
